
import { RoutineItem, Translations } from './types';

export const ROUTINE_ITEMS: RoutineItem[] = [
  // Salah Fardh
  { id: 'fajr', category: 'salah_fardh', labelKey: 'fajr', variant: 'virtue' },
  { id: 'dhuhr', category: 'salah_fardh', labelKey: 'dhuhr', variant: 'virtue' },
  { id: 'asr', category: 'salah_fardh', labelKey: 'asr', variant: 'virtue' },
  { id: 'maghrib', category: 'salah_fardh', labelKey: 'maghrib', variant: 'virtue' },
  { id: 'isha', category: 'salah_fardh', labelKey: 'isha', variant: 'virtue' },
  
  // Salah Nawafil
  { id: 'tahajjud', category: 'salah_nawafil', labelKey: 'tahajjud', variant: 'virtue' },
  { id: 'ishraq', category: 'salah_nawafil', labelKey: 'ishraq', variant: 'virtue' },
  { id: 'duha', category: 'salah_nawafil', labelKey: 'duha', variant: 'virtue' },
  { id: 'awwabin', category: 'salah_nawafil', labelKey: 'awwabin', variant: 'virtue' },
  
  // Tilawat
  { id: 'yaseen', category: 'tilawat', labelKey: 'yaseen', variant: 'virtue' },
  { id: 'mulk', category: 'tilawat', labelKey: 'mulk', variant: 'virtue' },
  { id: 'sajdah', category: 'tilawat', labelKey: 'sajdah', variant: 'virtue' },
  { id: 'waqiah', category: 'tilawat', labelKey: 'waqiah', variant: 'virtue' },
  { id: 'kahf', category: 'tilawat', labelKey: 'kahf', isFridayOnly: true, variant: 'virtue' },
  
  // Character & Ethics (New Section)
  { id: 'halal_sustenance', category: 'ethics', labelKey: 'halal_sustenance', variant: 'virtue' },
  { id: 'good_character', category: 'ethics', labelKey: 'good_character', variant: 'virtue' },
  { id: 'modesty', category: 'ethics', labelKey: 'modesty', variant: 'virtue' },

  // Habits
  { id: 'dhikr', category: 'habits', labelKey: 'dhikr', variant: 'virtue' },
  { id: 'exercise', category: 'habits', labelKey: 'exercise', variant: 'virtue' },
  { id: 'meditation', category: 'habits', labelKey: 'meditation', variant: 'virtue' },
  { id: 'family', category: 'habits', labelKey: 'family', variant: 'virtue' },

  // Avoidance (Vices)
  { id: 'backbiting', category: 'avoidance', labelKey: 'backbiting', variant: 'vice' },
  { id: 'vulgarity', category: 'avoidance', labelKey: 'vulgarity', variant: 'vice' },
  { id: 'major_sins', category: 'avoidance', labelKey: 'major_sins', variant: 'vice' },
  { id: 'evil_thoughts', category: 'avoidance', labelKey: 'evil_thoughts', variant: 'vice' },
  { id: 'against_sunnah', category: 'avoidance', labelKey: 'against_sunnah', variant: 'vice' },
  { id: 'bad_nazri', category: 'avoidance', labelKey: 'bad_nazri', variant: 'vice' },
  { id: 'lying', category: 'avoidance', labelKey: 'lying', variant: 'vice' },
  { id: 'theft', category: 'avoidance', labelKey: 'theft', variant: 'vice' },
  { id: 'anger', category: 'avoidance', labelKey: 'anger', variant: 'vice' },
];

export const TRANSLATIONS: Translations = {
  en: {
    title: 'Routine Check',
    score_label: 'Score',
    salah_fardh: 'Five Daily Fardh',
    salah_nawafil: 'Voluntary Nawafil',
    tilawat: 'Daily Tilawat',
    habits: 'Daily Habits',
    avoidance: 'Things to Avoid',
    ethics: 'Ethics & Character',
    reset_confirm: 'Reset progress for today?',
    download_report: 'Download Report',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    notes_label: 'Daily Reflections',
    notes_placeholder: 'Write any good or bad deeds not mentioned above...',
    reset_button: 'Reset Today\'s Progress',
    fajr: 'Fajr',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghrib',
    isha: 'Isha',
    tahajjud: 'Tahajjud',
    ishraq: 'Ishraq',
    duha: 'Duha',
    awwabin: 'Awwabin',
    yaseen: 'Surah Yaseen',
    mulk: 'Surah Al-Mulk',
    sajdah: 'Surah As-Sajdah',
    waqiah: 'Surah Al-Waqi\'ah',
    kahf: 'Surah Al-Kahf',
    dhikr: 'Dhikr',
    exercise: 'Walk / Exercise',
    meditation: 'Meditation',
    family: 'Parents / Family Time',
    halal_sustenance: 'Halal Sustenance',
    good_character: 'Good Manners',
    modesty: 'Modesty / Haya',
    backbiting: 'Backbiting',
    vulgarity: 'Vulgarity / Bad Language',
    major_sins: 'Major Sins (Kaba\'ir)',
    evil_thoughts: 'Evil Thoughts / Intentions',
    against_sunnah: 'Actions Against Sunnah',
    theft: 'Theft / Stealing',
    bad_nazri: 'Bad Nazri (Lower Gaze)',
    lying: 'Lying',
    anger: 'Unjustified Anger',
  },
  ur: {
    title: 'روٹین چیک',
    score_label: 'سکور',
    salah_fardh: 'پانچ نمازیں',
    salah_nawafil: 'نوافل',
    tilawat: 'تلاوتِ قرآن',
    habits: 'روزانہ کی عادات',
    avoidance: 'اجتناب (جن سے بچنا ہے)',
    ethics: 'اخلاقیات و کردار',
    reset_confirm: 'کیا آپ آج کی پیش رفت دوبارہ شروع کرنا چاہتے ہیں؟',
    download_report: 'رپورٹ ڈاؤن لوڈ کریں',
    daily: 'روزانہ',
    weekly: 'ہفتہ وار',
    monthly: 'ماہانہ',
    notes_label: 'روزانہ کے تاثرات',
    notes_placeholder: 'کوئی بھی نیک یا بری بات یہاں درج کریں...',
    reset_button: 'آج کی پیش رفت ری سیٹ کریں',
    fajr: 'فجر',
    dhuhr: 'ظہر',
    asr: 'عصر',
    maghrib: 'مغرب',
    isha: 'عشاء',
    tahajjud: 'تہجد',
    ishraq: 'اشراق',
    duha: 'چاشت (ضحی)',
    awwabin: 'اوابین',
    yaseen: 'سورہ یٰسین',
    mulk: 'سورہ الملک',
    sajdah: 'سورہ السجدہ',
    waqiah: 'سورہ الواقعہ',
    kahf: 'سورہ الکہف',
    dhikr: 'ذکر و اذکار',
    exercise: 'ورزش / واک',
    meditation: 'مراقبہ',
    family: 'والدین / گھر والوں کا وقت',
    halal_sustenance: 'رزق حلال',
    good_character: 'با اخلاق',
    modesty: 'با حیاء',
    backbiting: 'غیبت',
    vulgarity: 'بدزبانی',
    major_sins: 'کبیرہ گناہ',
    evil_thoughts: 'بدخیالی',
    against_sunnah: 'خلاف سنت کام',
    theft: 'چوری / بددیانتی',
    bad_nazri: 'بد نظری',
    lying: 'جھوٹ',
    anger: 'بلاوجہ غصہ',
  },
  hi: {
    title: 'रूटिन चेक',
    score_label: 'स्कोर',
    salah_fardh: 'पाँच फ़र्ज़ नमाज़ें',
    salah_nawafil: 'नवाफिल',
    tilawat: 'दैनिक तिलावत',
    habits: 'दैनिक आदतें',
    avoidance: 'बचने योग्य बातें',
    ethics: 'नैतिकता और चरित्र',
    reset_confirm: 'क्या आप आज की प्रगति रीसेट करना चाहते हैं?',
    download_report: 'रिपोर्ट डाउनलोड करें',
    daily: 'दैनिक',
    weekly: 'साप्ताहिक',
    monthly: 'मासिक',
    notes_label: 'दैनिक चिंतन',
    notes_placeholder: 'कोई भी अच्छी या बुरी बात यहाँ लिखें...',
    reset_button: 'आज की प्रगति रीसेट करें',
    fajr: 'फज्र',
    dhuhr: 'ज़ुहर',
    asr: 'अस्र',
    maghrib: 'मग़रिब',
    isha: 'ईशा',
    tahajjud: 'तहज्जुद',
    ishraq: 'इशराक',
    duha: 'दुहा',
    awwabin: 'अववाबीन',
    yaseen: 'सूरह यासीन',
    mulk: 'सूरह अल-मुल्क',
    sajdah: 'सूरह अस-सजदा',
    waqiah: 'सूरह अल-वक़िआ',
    kahf: 'सूरह अल-कहफ़',
    dhikr: 'ज़िक्र',
    exercise: 'व्यायाम / सैर',
    meditation: 'ध्यान (मेडिटेशन)',
    family: 'परिवार का समय',
    halal_sustenance: 'हलाल रिज़्क़',
    good_character: 'अच्छा आचरण',
    modesty: 'मर्यादा / हया',
    backbiting: 'चुगली (बैकबائٹنگ)',
    vulgarity: 'अपशब्द / गाली-गलौज',
    major_sins: 'बड़े पाप (कबीरा)',
    evil_thoughts: 'बुरे विचार / नीयत',
    against_sunnah: 'सुन्नत के खिलाफ कार्य',
    theft: 'चोरी',
    bad_nazri: 'बुरी नज़र',
    lying: 'झूठ',
    anger: 'अकारण क्रोध',
  },
  ar: {
    title: 'مراجعة الروتين',
    score_label: 'النتيجة',
    salah_fardh: 'الصلوات الخمس',
    salah_nawafil: 'النوافل',
    tilawat: 'التلاوة اليومية',
    habits: 'العادات اليومية',
    avoidance: 'نواهي يجب تجنبها',
    ethics: 'الأخلاق والقيم',
    reset_confirm: 'هل تريد إعادة ضبط تقدم اليوم؟',
    download_report: 'تحميل التقرير',
    daily: 'يومي',
    weekly: 'أسبوعي',
    monthly: 'شهري',
    notes_label: 'تأملات يومية',
    notes_placeholder: 'اكتب أي عمل خير أو شر لم يذكر أعلاه...',
    reset_button: 'إعادة تعيين تقدم اليوم',
    fajr: 'الفجر',
    dhuhr: 'الظهر',
    asr: 'العصر',
    maghrib: 'المغرب',
    isha: 'العشاء',
    tahajjud: 'التہجد',
    ishraq: 'الإشراق',
    duha: 'الضحى',
    awwabin: 'الأوابين',
    yaseen: 'سورة يس',
    mulk: 'سورة الملك',
    sajdah: 'سورة السجدة',
    waqiah: 'سورة الواقعة',
    kahf: 'سورة الكهف',
    dhikr: 'الأذكار',
    exercise: 'الرياضة / المشي',
    meditation: 'التأمل',
    family: 'وقت العائلة / الوالدين',
    halal_sustenance: 'الرزق الحلال',
    good_character: 'حسن الخلق',
    modesty: 'الحياء',
    backbiting: 'الغيبة',
    vulgarity: 'بذاءة اللسان',
    major_sins: 'الكبائر',
    evil_thoughts: 'سوء الظن / أفكار سيئة',
    against_sunnah: 'أفعال مخالفة للسنة',
    theft: 'السرقة',
    bad_nazri: 'غض البصر',
    lying: 'الكذب',
    anger: 'الغضب غير المبرر',
  }
};
